Initial commit, add coin and generated files.
ElrondNetwork/wallet-core pull request #1
Opened 2020-04-11 18:27 UTC by andreibancioiu

## Description

## Testing instructions

## Types of changes

## Checklist

- [ ] Prefix PR title with `[WIP]` if necessary.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description (e.g. 'Fixes #444 ).

2020-04-23 07:03 UTC, AdoAdoAdo requested changes

2020-04-23 07:03 UTC, AdoAdoAdo commented on include/TrustWalletCore/TWCoinType.h
> +    TWCoinTypeElrond = 2003,
update the coin type

2020-04-23 07:03 UTC, AdoAdoAdo commented on tests/Elrond/TestAccounts.h
> +const auto CAROL_PUBKEY_HEX = "2cf945faf0162ceede93fe3addda83fe2ebe2041f8a70b2521767044638fa29f";
newline at eof

2020-04-23 07:03 UTC, AdoAdoAdo commented on android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/elrond/TestElrondAddress.kt
> +        assertEquals(expected.description(), address.description())
I guess here aliceBech32 should be identical to expected.description()
is there a need to create "expected"?

2020-04-23 07:03 UTC, AdoAdoAdo commented on coins.json
> +        "derivationPath": "m/44'/2003'/0'",
update derivation path

2020-04-23 07:03 UTC, AdoAdoAdo commented on src/Elrond/Address.h
> +    Address(const PublicKey& publicKey) : Bech32Address(hrp, publicKey.bytes) {}
is this correct?
don't we need a hasher and call Bech32Address(hrp, *hasher*, publicKey) ?

2020-04-23 07:03 UTC, AdoAdoAdo commented on src/Elrond/Signer.cpp
> +    auto signableAsString = Elrond::serializeTransactionToSignableString(input.transaction());
I think Elrond qualifier not needed here as it is already in scope

2020-04-23 07:03 UTC, AdoAdoAdo commented on src/Elrond/Signer.cpp
> +    auto serializedTransaction = Elrond::serializeSignedTransaction(input.transaction(), encodedSignature);
I think Elrond qualifier not needed here as it is already in scope

2020-04-23 07:03 UTC, AdoAdoAdo commented on src/Elrond/Signer.cpp
> +    auto output = Signer::sign(input);
I think Signer qualifier is not needed

2020-04-23 08:12 UTC, camilbancioiu requested changes

2020-04-23 08:12 UTC, camilbancioiu commented on tests/Bech32AddressTests.cpp
> +    ASSERT_FALSE(Bech32Address::isValid("terd19nu5t7hszckwah5nlcadmk5rlchtugzplznskffpwecygcu0520s9tnyy0", "erd"));
xerd

2020-04-23 08:12 UTC, camilbancioiu commented on tests/CoinAddressValidationTests.cpp
> +    EXPECT_FALSE(validateAddress(TWCoinTypeElrond, "terd1l453hd0gt5gzdp7czpuall8ggt2dcv5zwmfdf3sd3lguxseux2fsmsgldz"));
xerd

2020-04-23 08:12 UTC, camilbancioiu commented on tests/Elrond/AddressTests.cpp
> +    ASSERT_FALSE(Address::isValid("nerd10z9xdugayn528ksaesdwlhf006fw5sg2qmmm0h52fvxczwgesyvq5pwemr"));
xerd

2020-04-23 09:48 UTC, andreibancioiu commented on tests/Elrond/TestAccounts.h
> +const auto CAROL_PUBKEY_HEX = "2cf945faf0162ceede93fe3addda83fe2ebe2041f8a70b2521767044638fa29f";
Fixed.

2020-04-23 10:20 UTC, andreibancioiu commented on src/Elrond/Address.h
> +    Address(const PublicKey& publicKey) : Bech32Address(hrp, publicKey.bytes) {}
As discussed, we use `bech32(pubKey)`, not `bech32(hash(pubKey))`.

2020-04-23 10:29 UTC, andreibancioiu commented on src/Elrond/Signer.cpp
> +    auto signableAsString = Elrond::serializeTransactionToSignableString(input.transaction());
Fixed.

2020-04-23 10:30 UTC, andreibancioiu commented on src/Elrond/Signer.cpp
> +    auto output = Signer::sign(input);
Fixed.

2020-04-23 10:31 UTC, andreibancioiu commented on tests/Bech32AddressTests.cpp
> +    ASSERT_FALSE(Bech32Address::isValid("terd19nu5t7hszckwah5nlcadmk5rlchtugzplznskffpwecygcu0520s9tnyy0", "erd"));
Fixed.

2020-04-23 10:31 UTC, andreibancioiu commented on tests/CoinAddressValidationTests.cpp
> +    EXPECT_FALSE(validateAddress(TWCoinTypeElrond, "terd1l453hd0gt5gzdp7czpuall8ggt2dcv5zwmfdf3sd3lguxseux2fsmsgldz"));
Fixed.

2020-04-23 10:31 UTC, andreibancioiu commented on tests/Elrond/AddressTests.cpp
> +    ASSERT_FALSE(Address::isValid("nerd10z9xdugayn528ksaesdwlhf006fw5sg2qmmm0h52fvxczwgesyvq5pwemr"));
Fixed.

2020-04-23 10:32 UTC, andreibancioiu commented on src/Elrond/Signer.cpp
> +    auto serializedTransaction = Elrond::serializeSignedTransaction(input.transaction(), encodedSignature);
Fixed.

2020-04-23 10:59 UTC, andreibancioiu commented on include/TrustWalletCore/TWCoinType.h
> +    TWCoinTypeElrond = 2003,
Fixed.

2020-04-23 10:59 UTC, andreibancioiu commented on coins.json
> +        "derivationPath": "m/44'/2003'/0'",
Fixed.

2020-04-23 11:16 UTC, andreibancioiu commented on android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/elrond/TestElrondAddress.kt
> +        assertEquals(expected.description(), address.description())
Fixed.

2020-04-23 12:09 UTC, camilbancioiu approved these changes

2020-04-23 13:06 UTC, AdoAdoAdo approved these changes

2020-04-28 12:17 UTC, andreibancioiu commented
We can close this PR, the official one is against the parent repository.

2020-04-28 12:17 UTC, closed without merging